const KEY='3l_crm_leads_v1',SESSION='3l_crm_session';
const $=s=>document.querySelector(s);const statuses=['Novo lead','Primeiro contato','Simulação enviada','Em negociação','Documentação','Venda fechada','Perdido'];
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}}function save(v){localStorage.setItem(KEY,JSON.stringify(v))}
function esc(v=''){return String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}function phone(v=''){return v.replace(/\D/g,'')}
function showApp(){ $('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');render() }
if(sessionStorage.getItem(SESSION)==='ok')showApp();
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();if($('#loginUser').value==='admin'&&$('#loginPass').value==='3L2026'){sessionStorage.setItem(SESSION,'ok');showApp()}else $('#loginMsg').textContent='Usuário ou senha incorretos.'});
$('#logoutBtn').onclick=()=>{sessionStorage.removeItem(SESSION);location.reload()};
function metrics(leads){const vendas=leads.filter(x=>x.status==='Venda fechada').length,ativos=leads.filter(x=>!['Novo lead','Venda fechada','Perdido'].includes(x.status)).length;$('#mNovos').textContent=leads.filter(x=>x.status==='Novo lead').length;$('#mAndamento').textContent=ativos;$('#mVendas').textContent=vendas;$('#mConversao').textContent=leads.length?Math.round(vendas/leads.length*100)+'%':'0%'}
function render(){let leads=load();metrics(leads);const q=$('#searchInput')?.value.toLowerCase()||'',sf=$('#statusFilter')?.value||'';const filtered=leads.filter(x=>(!sf||x.status===sf)&&(!q||[x.nome,x.telefone,x.cidade,x.tipo].join(' ').toLowerCase().includes(q)));$('#leadList').innerHTML=filtered.length?filtered.map(x=>`<article class="lead-card"><div><h3>${esc(x.nome)}</h3><p>${esc(x.telefone)} · ${esc(x.cidade||'Cidade não informada')}</p></div><div><span class="badge">${esc(x.status)}</span><p>${esc(x.tipo||'Não informado')}</p></div><div><strong>${esc(x.valor||'Valor não informado')}</strong><p>${x.proximoContato?'Retorno: '+new Date(x.proximoContato+'T12:00').toLocaleDateString('pt-BR'):'Sem retorno agendado'}</p></div><div class="actions"><a title="WhatsApp" target="_blank" href="https://wa.me/55${phone(x.telefone)}">✆</a><button title="Editar" onclick="editLead('${x.id}')">✎</button></div></article>`).join(''):'<div class="empty">Nenhum lead encontrado.</div>';renderAgenda(leads);renderReport(leads)}
function renderAgenda(leads){const v=leads.filter(x=>x.proximoContato).sort((a,b)=>a.proximoContato.localeCompare(b.proximoContato));$('#agendaList').innerHTML=v.length?v.map(x=>`<div class="agenda-item"><span><b>${esc(x.nome)}</b><br><small>${esc(x.telefone)}</small></span><strong>${new Date(x.proximoContato+'T12:00').toLocaleDateString('pt-BR')}</strong></div>`).join(''):'<div class="empty">Nenhum retorno agendado.</div>'}
function renderReport(leads){$('#reportList').innerHTML=statuses.map(s=>`<div class="report-row"><span>${s}</span><b>${leads.filter(x=>x.status===s).length}</b></div>`).join('')}
$('#searchInput').oninput=render;$('#statusFilter').onchange=render;
document.querySelectorAll('aside nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('aside nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');['leads','agenda','relatorios'].forEach(s=>$('#'+s+'Section').classList.toggle('hidden',s!==b.dataset.section))});
function openDialog(x={}){$('#leadId').value=x.id||'';$('#fNome').value=x.nome||'';$('#fTelefone').value=x.telefone||'';$('#fEmail').value=x.email||'';$('#fCidade').value=x.cidade||'';$('#fTipo').value=x.tipo||'Imóvel';$('#fValor').value=x.valor||'';$('#fParcela').value=x.parcela||'';$('#fStatus').value=x.status||'Novo lead';$('#fProximo').value=x.proximoContato||'';$('#fObs').value=x.observacoes||'';$('#dialogTitle').textContent=x.id?'Editar lead':'Novo lead';$('#deleteBtn').classList.toggle('hidden',!x.id);$('#leadDialog').showModal()}
$('#newLeadBtn').onclick=()=>openDialog();$('#closeDialog').onclick=()=>$('#leadDialog').close();window.editLead=id=>openDialog(load().find(x=>x.id===id));
$('#leadForm').addEventListener('submit',e=>{e.preventDefault();let leads=load(),id=$('#leadId').value,old=leads.find(x=>x.id===id);const x={...(old||{}),id:id||crypto.randomUUID?.()||String(Date.now()),nome:$('#fNome').value.trim(),telefone:$('#fTelefone').value.trim(),email:$('#fEmail').value.trim(),cidade:$('#fCidade').value.trim(),tipo:$('#fTipo').value,valor:$('#fValor').value.trim(),parcela:$('#fParcela').value.trim(),status:$('#fStatus').value,proximoContato:$('#fProximo').value,observacoes:$('#fObs').value.trim(),origem:old?.origem||'Cadastro manual',criadoEm:old?.criadoEm||new Date().toISOString(),atualizadoEm:new Date().toISOString()};leads=id?leads.map(y=>y.id===id?x:y):[x,...leads];save(leads);$('#leadDialog').close();render()});
$('#deleteBtn').onclick=()=>{const id=$('#leadId').value;if(id&&confirm('Excluir este lead?')){save(load().filter(x=>x.id!==id));$('#leadDialog').close();render()}};
$('#exportBtn').onclick=()=>{const rows=load(),cols=['nome','telefone','email','cidade','tipo','valor','parcela','status','proximoContato','origem','criadoEm'],csv=[cols.join(';'),...rows.map(r=>cols.map(c=>'"'+String(r[c]||'').replace(/"/g,'""')+'"').join(';'))].join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv'}));a.download='leads-3l-investimentos.csv';a.click()};
